server:
 port: 80
 servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/feman_cartoon
    username: root
    password: luzx
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true